use_frameworks!

platform :ios, '8.0'

target 'TTTabbarController_Example' do
  pod 'TTTabbarController', :path => '../'

  target 'TTTabbarController_Tests' do
    inherit! :search_paths

    
  end
end
